# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: coupon-service package

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_OWNER: nhnacademy-be12-trillion
  IMAGE_NAME: book
  JAVA_VERSION: 21
  DEPLOY_DIR: ~/msa-project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven


      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Sonarqube
#      - name : Run SonarQube
#        run : mvn sonar:sonar -Dsonar.projectKey=nhnacademy-be12-trillion-coupon -Dsonar.host.url=${{secrets.SONAR_HOST}} -Dsonar.login=${{secrets.SONAR_TOKEN}}
      - name: GitHub Packages 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_OWNER }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: 이미지 태그 세팅
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest # latest 태그 고정

      - name: 도커 이미지 빌드 & 푸시
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: 파일 전송 및 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            SERVICE_NAME1="coupon-peer"

            echo "SSH 접속 및 디렉토리 이동..."
            mkdir -p ${{ env.DEPLOY_DIR }}
            cd ${{ env.DEPLOY_DIR }}

            echo "Docker Registry 로그인"
            echo ${{ secrets.GHCR_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_OWNER }} --password-stdin

            echo "Coupon-service 업데이트 시작"

            echo "최신 이미지 Pull 및 Peer 재시작..."
            docker-compose pull ${SERVICE_NAME1}
            docker-compose up -d --no-deps ${SERVICE_NAME1}
            
            echo "Coupon-Service 롤링 업데이트 완료!"

            echo "Docker Registry 로그아웃..."
            docker logout ${{ env.REGISTRY }}

            echo "도서 서비스 배포 완료!"